### ISSUE TITLE
Install Fails with server 500 error

### ISSUE THREAD

**Issue by jimmck** [davestewart/laravel-sketchpad#3]
When installing the sketchpad folders displays Please wait...

JS Console shows a Internal Server error 500

rc1

**Comment by davestewart** [comment]
OK, I'll need some more info.

If you can provide a screenshot with:

- the stage you are at installing Sketchpad
- the Chrome debugger tools open, showing:
    - The "Network" tab, with the "Response" tab showing (so I can see Laravel's error)
    - Also, press The Escape key so that the mini-console panel shows (so I can see any JS errors)

**Comment by jimmck** [comment]
Dave,
There are no displayed errors on the browser. As stated Installer Was Installing Sketch Pad Folders (I believe Step 2). Here is an idea, a setup log file.  Here is the log entry from the laravel.log

```
#[2017-04-04 01:32:44] local.ERROR: ErrorException: file_put_contents(/Users/jimm/laravel-54/composer.json): failed to open stream: Permission denied in /Users/jimm/laravel-54/vendor/davestewart/sketchpad/src/objects/install/JSON.php:94
Stack trace:52 {main}  
```

The documentation states it will guide the User through errors, it does nothing. This is a development tool, it should be able to handle errors and display the errors to the developer in a meaningful way. A Sketch Pad should let someone design trough trial and error. You need to anticipate that. 

Sadly this is not ready for release.

**Comment by davestewart** [comment]
Firstly, sorry you're getting such a hard time of it, and thanks for plugging through.

Well I understood from the last ticket that the errors you were having weren't anything to do with Sketchpad? I've tested everything on 4 other machines, and a couple of VMs so far and they all installed / ran OK.

But, yes, still frustrating for you :(

The installer actually has a **ton** of error checking in, and checks for all steps of the install, like copying folders, whether content is was copied OK, etc, etc, and displays a helpful log, allowing the user to go back, etc:

![image](https://cloud.githubusercontent.com/assets/132681/24674462/661edca6-1973-11e7-96f2-abed6b7772ea.png)

But this one is a good catch, it's a permissions issue on `composer.json`; I'll add in another check for that. 

If you want to get over the last (hopefully!) hurdle you can try changing the permissions on `composer.json` or updating it manually:

```
        "psr-4": {
            "App\\": "app/",
            "sketchpad\\": "sketchpad/"
        },

```

Or if you've had enough, you can sack it all off; I won't blame you :)

**Comment by jimmck** [comment]
I updated the file permissions on the composer file and reran setup. I get this error. I have run dumpautoload several times.

<img width="1136" alt="screen shot 2017-04-04 at 7 42 31 pm" src="https://cloud.githubusercontent.com/assets/2323131/24683743/1c2c9466-196f-11e7-98f8-846e9d57cfc3.png">

**Comment by davestewart** [comment]
Very well done for persevering :)

I *think* the reason it says composer autoload hasn't generated files (it probably has) is that Composer seems to spit out different messages depending on the version. I've actually updated this in the latest build so it should report accurately (I'm basically parsing the output from the console return message). 

BUT... if you go straight to `/sketchpad` and it should all be running :)

Again, really sorry it was such a hassle for you, and thanks for sticking with it!

**Comment by jimmck** [comment]
When I click on Example Start Here ....

<img width="1228" alt="screen shot 2017-04-05 at 12 05 52 am" src="https://cloud.githubusercontent.com/assets/2323131/24689334/c6348648-1993-11e7-8278-fc4381fc8532.png">

**Comment by davestewart** [comment]
Caused by a regression in the latest build unfortunately! Fixed last night.

**Comment by davestewart** [comment]
Another build coming in the next hour or so BTW...

**Comment by davestewart** [comment]
OK, I'm actually now checking `vendor/composer/autoload_psr4.php` for the presence of the new custom namespace, so that should be much more solid, save for Composer changing the filename of that file.

**Comment by jimmck** [comment]
Just installed rc3 and we have moved onto this.

<img width="1211" alt="screen shot 2017-04-05 at 1 42 10 pm" src="https://cloud.githubusercontent.com/assets/2323131/24718954/ea93665e-1a05-11e7-85d0-e53049a55817.png">

**Comment by davestewart** [comment]
Re-run the setup routine :)

**Comment by jimmck** [comment]
Yes, working now. I am hitting all defaults now but rerunning setup in the future may become tedious if I change stuff. As an aside, is that you in April Net Magazine? You can close this out.

I do like many of the ideas here as needing a quick way to spin up a page front and back is a pain at times.

Thanks

**Comment by davestewart** [comment]
Yeah, that's me :)

Nah, the error in the example controller was just a hangover from changing from config to temp storage for the settings. Unfortunately the example controller (generated from a template) hadn't been updated. All future updates should be solid.

**Comment by davestewart** [comment]
PS, thanks for sticking with it! I appreciate it

**Comment by jimmck** [comment]
No problem. I like the idea and have thought along these lines. I am very backend and process oriented. I once added a Splash Screen to a trader dashboard and they said how do I turn this off. Nice portfolio page. I am sure to have some more feedback.

Jim
