### ISSUE TITLE
errors installation failed.

### ISSUE THREAD

**Issue by vipin733** [davestewart/laravel-sketchpad#4]
i just install on my local machine when i visit https://bae.dev/sketchpad/  its give errors

Whoops, looks like something went wrong

**Comment by davestewart** [comment]
Post a screenshot please

**Comment by vipin733** [comment]
my mistake, but now facing new error , its giving
![2](https://cloud.githubusercontent.com/assets/10106412/24722738/80a01352-1a62-11e7-9d01-26b8bff75b12.PNG)
 errors while   setup

**Comment by davestewart** [comment]
Oh dear! The first error is odd. Sketchpad saves data to the storage directory. Without that, we're in trouble. Are your permissions there writable? I can add a test to the setup process if you think not.

In the meantime, can you set it as writable and try again?

**Comment by davestewart** [comment]
As for the example controller... I'll test on a fresh install. What setup are you on?

**Comment by vipin733** [comment]
I'm using windows? and I did not get "What setup are you on?" what mean of this

**Comment by davestewart** [comment]
I mean what OS, VM, that kind of thing, but don't worry - I've worked out what the bug is and will be releasing a fix shortly

**Comment by vipin733** [comment]
yes I'm using windows 7 and laragon server
