### ISSUE TITLE
Namespace issue on windows using laragon

### ISSUE THREAD

**Issue by webloper** [davestewart/laravel-sketchpad#52]
![fireshot capture 1 - sketchpad - setup - http___laravel dev_sketchpad_setup](https://cloud.githubusercontent.com/assets/334000/26434887/07d0011a-4129-11e7-8540-9e71852f4b7d.png)

and this is the namespace its generating

> 

```
namespace C:\laragon\www\laravel\app\Http\Controllers;
```

**Comment by clovenlife** [comment]
also experiencing this issue on windows using Xampp

**Comment by davestewart** [comment]
Hi guys,

Rather annoying this one, as it seems to be intermittent.

Just click "Next" again and all should be well.

I think it's an issue with Composer not loading the new namespace correctly on the first go. I actually put in code to cope with this in the Beta, but either I didn't solve it, or it's cropped up again.

Let me know if that does or doesn't solve it, and I'll look again.

**Comment by davestewart** [comment]
Actually, think this is going to be me not testing on Windows, and my code to resolve namespaces from file paths using windows backslashes is probably borked.

I'll look to fix this in the next 24 hours, sorry for the inconvenience!

**Comment by clovenlife** [comment]
I did try to click "next" but it wouldn't let me so I just returned pass on the install check to bypass it. It wanted to set the namespace to the actual file location as I would find it in Windows but the namespace set for all my controllers is set as "App\Http\Controllers" 
Using these two workarounds has let me continue to work with sketchpad

**Comment by davestewart** [comment]
Just to update you fellas, I've just tried installing on Parallels, but served using Valet's `share` command.

Install worked correctly, first time. I'll take another look at the namespacing code again; hopefully I can get it to break, then mend it.

**Comment by davestewart** [comment]
OK, bug squished. Just do the following to update to 1.2.7:

```
composer update davestewart/sketchpad
```

If it isn't fixed, just let me know here.

**Comment by clovenlife** [comment]
Did a fresh install and everything went smoothly. Namespace in ExampleController.php was correct out of the box
Thanks!
