### ISSUE TITLE
Using sketchpad in subfolder project on xampp

### ISSUE THREAD

**Issue by KuenzelIT** [davestewart/laravel-sketchpad#57]
Hi,

I'm having a problem using sketchpad with xampp. My project sits under localhost/Something/ . But Sketchpad tries to use localhost/sketchpad anyways, e.g. when loading lib.js: http://localhost/sketchpad/assets/js/lib.js

Is there some way to change this?

The url seems to be hardcoded in SketchpadConfig.php. Maybe we can move this to a config file?

I know this problem wouldn't be there with Homestead, but I can't change to Homestead right now.

Thanks!

**Comment by davestewart** [comment]
Hey,

The path is config actually :)

Because Sketchpad is configurable per-user, not per install, all settings are stored in `/storage/sketchpad/settings.json`.

If you edit the `assets` path there, does that fix your problem?

This should be a relative path from your project's route.

**Comment by KuenzelIT** [comment]
Hey,

ok, I see that config file now, but it's in the following directory:
`\vendor\davestewart\sketchpad\package\config`

I shouldn't change the path there, do I?

Just to let you know, I never saw the setup page, only a blank page with the title "Sketchpad".

Thank you for your help!

**Comment by davestewart** [comment]
Oh, that's really strange; the setup process is supposed to take you through the whole thing!

If you want to try running it (Setup) again, just delete the `settings.json` file and re-run the fun.

The setup file you mentioned is the master (so don't change it!). You need to change the one in your app's `storage` folder.

Let me know if that works.

**Comment by KuenzelIT** [comment]
The problem is that I never got through the setup, the assets couldn't be found right at the first time. Maybe I'll change the path in the master file to get it running and change it back later on. I'll report back if it's working.

**Comment by davestewart** [comment]
Yeah, try the master path, and see how that goes.

Though if there's a problem with the setup, I'd like to solve it.

If you want to screen record the setup process and post it somewhere, it would help me see what you're seeing. If you have the time, make sure you have the JS console open so I can see what's going on :)

**Comment by KuenzelIT** [comment]
I didn't get far with changing the master config file, the behaviour didn't change.

When I go to /sketchpad, the page tries to load all those javascript and css files like this:
`GET http://localhost/sketchpad/assets/js/lib.js`

Which does fail, because my project is located under 
`http://localhost/PROJECT/public/sketchpad `

So the problem is just how the assets path is set.

I think the problem lies in the Setup.php file, line 67:
`'assets'    => $config->route . 'assets/',`

The url from config/app.php is not being used here.

What do you think?

**Comment by davestewart** [comment]
Tricky to tell without seeing your exact setup, but it looks like the problem is that you're using `localhost` incorrectly.

Localhost is effectively your XAMPP's "top-level" site, and operates as a site in itself, so for additional projects, i.e. `http://localhost/PROJECT/`, you should set these up as "virtual hosts" (if using apache), so you can run multiple sites:

- http://www.thegeekstuff.com/2011/07/Apache-Virtual-Host/

Does this sound like it might be the solution to your problem, or have I just misunderstood what you wrote?

**Comment by KuenzelIT** [comment]
That's probably a solution, but it should work without it anyways, since Laravel and a lot of other software works. :)

I may look for a solution and report back.

**Comment by KuenzelIT** [comment]
Alright I get it, so sketchpad needs a fixed url to be set up. Thanks for your help!

**Comment by davestewart** [comment]
Yeah, it's pretty standard :)

Take some time to get to know vhosts if you can't use Homestead, it does make your life easier!

**Comment by KuenzelIT** [comment]
I never needed it in years of web development. But you're probably right. :)

**Comment by KuenzelIT** [comment]
Alright, I set up virtual hosts and now the setup works. :)

**Comment by davestewart** [comment]
Welcome!

And, you're welcome :)
